services:
  acme:
    image: neilpang/acme.sh
    volumes:
      - ./cert:/cert/
      - ./acme.sh:/acme.sh
      - ./acme.sh-docker.sh:/acme.sh-docker.sh:ro
    entrypoint: 
    restart: always
    environment:
      - CF_Token=${CF_Token}
      - CF_Zone_ID=${CF_Zone_ID}
      - DNS_API=${DNS_API}
      - ACME_SH_EMAIL=${ACME_SH_EMAIL}
      - DOMAIN=${MXDOMAIN}
    command: sh ./acme.sh-docker.sh
    healthcheck:
      test: ["CMD", "sh", "-c", "[ -f /cert/cert.pem ] && openssl x509 -checkend 86400 -noout -in /cert/cert.pem"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: ghcr.io/yumusb/email_router:latest
    volumes:
      - ./config.yml:/app/config.yml:ro
      - ./cert:/cert/
    restart: always
    environment:
      - MXDOMAIN=${MXDOMAIN}
    ports:
      - "25:25"
      - "587:587"
    depends_on:
      acme:
        condition: service_healthy